
import "./globals.css";
export const metadata = {
  title: "CEP-Projects",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <main className="mt-20 lg:px-12">
          {children}
        </main>
      </body>
    </html>
  );
}
